### Install with 'brew bundle'
### If you don't want to upgrade to latest: `brew bundle install --no-upgrade`

# Common
brew 'atuin'
brew 'bash'
brew 'bash-completion'
brew 'bat'
brew 'btop'
brew 'cask'
brew 'colima'
brew 'curl'
brew 'direnv'
brew 'docker'
brew 'fzf'
brew 'git'
brew 'htop'
brew 'hunk'
brew 'jq'
brew 'k9s'
brew 'libxmlsec1'
brew 'neovim'
brew 'openssl'
brew 'pkgconfig'
brew 'podman'
brew 'pwgen'
brew 'ripgrep'
brew 'rsync'
brew 'sshuttle'
brew 'tmux'
brew 'watch'
brew 'wget'
brew 'yq'

# Languages
brew 'node'
brew 'python'
brew 'ruby'

# Services
brew 'postgresql'
brew 'redis'

cask '1password'
cask 'chromedriver'
# cask 'docker-desktop'
cask 'firefox'
cask 'gcloud-cli'
cask 'ghostty'
cask 'iterm2'
cask 'karabiner-elements'
cask 'maccy'
cask 'ngrok'
cask 'obsidian'
cask 'rectangle'
cask 'slack'
cask 'visual-studio-code'
